// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/accept-invitation" | "/[locale]/admin/agents" | "/[locale]/admin/dashboard" | "/[locale]/admin/dashboard/ingest" | "/[locale]/admin/dashboard/scraper" | "/[locale]/admin/deals" | "/[locale]/admin/intelligence" | "/[locale]/admin/leads" | "/[locale]/admin/observability" | "/[locale]/admin/onboarding" | "/[locale]/admin/operations/team" | "/[locale]/admin/outreach" | "/[locale]/admin/outreach/new" | "/[locale]/admin/pipeline" | "/[locale]/admin/revenue" | "/[locale]/admin/security/iam" | "/[locale]/admin/select-tenant" | "/[locale]/admin/settings/branding" | "/[locale]/auth/accept-invite" | "/[locale]/auth/forgot-password" | "/[locale]/auth/register-company" | "/[locale]/auth/sign-in" | "/[locale]/auth/sign-up" | "/[locale]/p/[slug]" | "/[locale]/pricing" | "/[locale]/privacy" | "/[locale]/sign-out"
type AppRouteHandlerRoutes = "/[locale]/api/admin/actions" | "/[locale]/api/admin/agents" | "/[locale]/api/admin/agents/[id]" | "/[locale]/api/admin/onboarding" | "/[locale]/api/admin/scrapers/run" | "/[locale]/api/admin/scrapers/schedules" | "/[locale]/api/admin/scrapers/status/[jobId]" | "/[locale]/api/admin/scrapers/trigger" | "/[locale]/api/auth/change-password" | "/[locale]/api/auth/logout" | "/[locale]/api/auth/register-company" | "/[locale]/api/auth/register-invite" | "/[locale]/api/auth/switch-tenant" | "/[locale]/api/auth/tenant" | "/[locale]/api/contact" | "/[locale]/api/leads/[id]/status" | "/[locale]/api/leads/ingest" | "/[locale]/api/v1/whatsapp" | "/api/admin/auditor" | "/api/admin/finops" | "/api/admin/invitations" | "/api/admin/metrics/log" | "/api/admin/metrics/vps" | "/api/agents" | "/api/analytics/heatmap" | "/api/appointments" | "/api/appointments/[id]" | "/api/auth-internal" | "/api/auth/[...nextauth]" | "/api/bridge/lead-intelligence" | "/api/chat/sales" | "/api/finops/budget" | "/api/finops/report" | "/api/health" | "/api/invitations/accept" | "/api/leads/[id]/intelligence" | "/api/leads/brief" | "/api/leads/brief/[leadId]" | "/api/leads/ingest" | "/api/leads/intelligence/pending" | "/api/leads/pipeline" | "/api/leads/pipeline/[status]" | "/api/leads/score" | "/api/metrics" | "/api/observability/health" | "/api/observability/metrics" | "/api/observability/traces" | "/api/outreach/campaigns" | "/api/outreach/campaigns/[id]/enroll" | "/api/outreach/campaigns/[id]/process" | "/api/outreach/campaigns/[id]/stats" | "/api/payments/cancel-subscription" | "/api/payments/change-plan" | "/api/payments/create-subscription" | "/api/payments/subscription-status" | "/api/proposals" | "/api/proposals/[id]" | "/api/proposals/[id]/pdf" | "/api/proposals/[id]/send" | "/api/rum/events" | "/api/rum/summary" | "/api/webhooks/mercadopago"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/[locale]/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/accept-invitation": { "locale": string; }
  "/[locale]/admin": { "locale": string; }
  "/[locale]/admin/agents": { "locale": string; }
  "/[locale]/admin/dashboard": { "locale": string; }
  "/[locale]/admin/dashboard/ingest": { "locale": string; }
  "/[locale]/admin/dashboard/scraper": { "locale": string; }
  "/[locale]/admin/deals": { "locale": string; }
  "/[locale]/admin/intelligence": { "locale": string; }
  "/[locale]/admin/leads": { "locale": string; }
  "/[locale]/admin/observability": { "locale": string; }
  "/[locale]/admin/onboarding": { "locale": string; }
  "/[locale]/admin/operations/team": { "locale": string; }
  "/[locale]/admin/outreach": { "locale": string; }
  "/[locale]/admin/outreach/new": { "locale": string; }
  "/[locale]/admin/pipeline": { "locale": string; }
  "/[locale]/admin/revenue": { "locale": string; }
  "/[locale]/admin/security/iam": { "locale": string; }
  "/[locale]/admin/select-tenant": { "locale": string; }
  "/[locale]/admin/settings/branding": { "locale": string; }
  "/[locale]/api/admin/actions": { "locale": string; }
  "/[locale]/api/admin/agents": { "locale": string; }
  "/[locale]/api/admin/agents/[id]": { "locale": string; "id": string; }
  "/[locale]/api/admin/onboarding": { "locale": string; }
  "/[locale]/api/admin/scrapers/run": { "locale": string; }
  "/[locale]/api/admin/scrapers/schedules": { "locale": string; }
  "/[locale]/api/admin/scrapers/status/[jobId]": { "locale": string; "jobId": string; }
  "/[locale]/api/admin/scrapers/trigger": { "locale": string; }
  "/[locale]/api/auth/change-password": { "locale": string; }
  "/[locale]/api/auth/logout": { "locale": string; }
  "/[locale]/api/auth/register-company": { "locale": string; }
  "/[locale]/api/auth/register-invite": { "locale": string; }
  "/[locale]/api/auth/switch-tenant": { "locale": string; }
  "/[locale]/api/auth/tenant": { "locale": string; }
  "/[locale]/api/contact": { "locale": string; }
  "/[locale]/api/leads/[id]/status": { "locale": string; "id": string; }
  "/[locale]/api/leads/ingest": { "locale": string; }
  "/[locale]/api/v1/whatsapp": { "locale": string; }
  "/[locale]/auth/accept-invite": { "locale": string; }
  "/[locale]/auth/forgot-password": { "locale": string; }
  "/[locale]/auth/register-company": { "locale": string; }
  "/[locale]/auth/sign-in": { "locale": string; }
  "/[locale]/auth/sign-up": { "locale": string; }
  "/[locale]/p/[slug]": { "locale": string; "slug": string; }
  "/[locale]/pricing": { "locale": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/sign-out": { "locale": string; }
  "/api/admin/auditor": {}
  "/api/admin/finops": {}
  "/api/admin/invitations": {}
  "/api/admin/metrics/log": {}
  "/api/admin/metrics/vps": {}
  "/api/agents": {}
  "/api/analytics/heatmap": {}
  "/api/appointments": {}
  "/api/appointments/[id]": { "id": string; }
  "/api/auth-internal": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/bridge/lead-intelligence": {}
  "/api/chat/sales": {}
  "/api/finops/budget": {}
  "/api/finops/report": {}
  "/api/health": {}
  "/api/invitations/accept": {}
  "/api/leads/[id]/intelligence": { "id": string; }
  "/api/leads/brief": {}
  "/api/leads/brief/[leadId]": { "leadId": string; }
  "/api/leads/ingest": {}
  "/api/leads/intelligence/pending": {}
  "/api/leads/pipeline": {}
  "/api/leads/pipeline/[status]": { "status": string; }
  "/api/leads/score": {}
  "/api/metrics": {}
  "/api/observability/health": {}
  "/api/observability/metrics": {}
  "/api/observability/traces": {}
  "/api/outreach/campaigns": {}
  "/api/outreach/campaigns/[id]/enroll": { "id": string; }
  "/api/outreach/campaigns/[id]/process": { "id": string; }
  "/api/outreach/campaigns/[id]/stats": { "id": string; }
  "/api/payments/cancel-subscription": {}
  "/api/payments/change-plan": {}
  "/api/payments/create-subscription": {}
  "/api/payments/subscription-status": {}
  "/api/proposals": {}
  "/api/proposals/[id]": { "id": string; }
  "/api/proposals/[id]/pdf": { "id": string; }
  "/api/proposals/[id]/send": { "id": string; }
  "/api/rum/events": {}
  "/api/rum/summary": {}
  "/api/webhooks/mercadopago": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/[locale]/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
