// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/[locale]/accept-invitation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/accept-invitation">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/accept-invitation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/agents">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/dashboard/ingest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/dashboard/ingest">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/dashboard/ingest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/dashboard/scraper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/dashboard/scraper">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/dashboard/scraper/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/deals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/deals">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/deals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/intelligence">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/leads">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/observability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/observability">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/observability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/operations/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/operations/team">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/operations/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/outreach/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/outreach/new">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/outreach/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/outreach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/outreach">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/outreach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/pipeline">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/revenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/revenue">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/revenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/security/iam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/security/iam">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/security/iam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/select-tenant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/select-tenant">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/select-tenant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/settings/branding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/branding">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/settings/branding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/auth/accept-invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/accept-invite">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/auth/accept-invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/auth/register-company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/register-company">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/auth/register-company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/auth/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/sign-in">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/auth/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/auth/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/sign-up">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/auth/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/p/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/p/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/p/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/sign-out/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sign-out">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/sign-out/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/admin/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/admin/actions">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/admin/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/admin/agents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/admin/agents/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/admin/agents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/admin/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/admin/agents">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/admin/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/admin/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/admin/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/admin/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/admin/scrapers/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/admin/scrapers/run">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/admin/scrapers/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/admin/scrapers/schedules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/admin/scrapers/schedules">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/admin/scrapers/schedules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/admin/scrapers/status/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/admin/scrapers/status/[jobId]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/admin/scrapers/status/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/admin/scrapers/trigger/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/admin/scrapers/trigger">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/admin/scrapers/trigger/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/auth/register-company/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/auth/register-company">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/auth/register-company/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/auth/register-invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/auth/register-invite">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/auth/register-invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/auth/switch-tenant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/auth/switch-tenant">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/auth/switch-tenant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/auth/tenant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/auth/tenant">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/auth/tenant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/leads/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/leads/[id]/status">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/leads/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/leads/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/leads/ingest">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/leads/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api/v1/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/v1/whatsapp">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api/v1/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/auditor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auditor">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/auditor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/finops/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finops">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/finops/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/invitations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invitations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/invitations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/metrics/log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/metrics/log">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/metrics/log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/metrics/vps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/metrics/vps">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/metrics/vps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/analytics/heatmap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/heatmap">> = Specific
  const handler = {} as typeof import("../../../src/app/api/analytics/heatmap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/appointments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/appointments/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/appointments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/appointments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/appointments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/appointments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth-internal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth-internal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth-internal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/bridge/lead-intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bridge/lead-intelligence">> = Specific
  const handler = {} as typeof import("../../../src/app/api/bridge/lead-intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/sales">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/finops/budget/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finops/budget">> = Specific
  const handler = {} as typeof import("../../../src/app/api/finops/budget/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/finops/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finops/report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/finops/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invitations/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations/accept">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invitations/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leads/[id]/intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/intelligence">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leads/[id]/intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leads/brief/[leadId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/brief/[leadId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leads/brief/[leadId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leads/brief/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/brief">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leads/brief/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leads/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/ingest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leads/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leads/intelligence/pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/intelligence/pending">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leads/intelligence/pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leads/pipeline/[status]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/pipeline/[status]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leads/pipeline/[status]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leads/pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/pipeline">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leads/pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leads/score/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/score">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leads/score/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/observability/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/observability/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/observability/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/observability/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/observability/metrics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/observability/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/observability/traces/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/observability/traces">> = Specific
  const handler = {} as typeof import("../../../src/app/api/observability/traces/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/outreach/campaigns/[id]/enroll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outreach/campaigns/[id]/enroll">> = Specific
  const handler = {} as typeof import("../../../src/app/api/outreach/campaigns/[id]/enroll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/outreach/campaigns/[id]/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outreach/campaigns/[id]/process">> = Specific
  const handler = {} as typeof import("../../../src/app/api/outreach/campaigns/[id]/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/outreach/campaigns/[id]/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outreach/campaigns/[id]/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/outreach/campaigns/[id]/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/outreach/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outreach/campaigns">> = Specific
  const handler = {} as typeof import("../../../src/app/api/outreach/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/cancel-subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/cancel-subscription">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/cancel-subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/change-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/change-plan">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/change-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/create-subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/create-subscription">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/create-subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/subscription-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/subscription-status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/subscription-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/proposals/[id]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals/[id]/pdf">> = Specific
  const handler = {} as typeof import("../../../src/app/api/proposals/[id]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/proposals/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/proposals/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/proposals/[id]/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals/[id]/send">> = Specific
  const handler = {} as typeof import("../../../src/app/api/proposals/[id]/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/proposals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals">> = Specific
  const handler = {} as typeof import("../../../src/app/api/proposals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rum/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rum/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rum/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rum/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rum/summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rum/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/mercadopago/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/mercadopago">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/mercadopago/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/[locale]/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
