-- CreateEnum
CREATE TYPE "AuditEventType" AS ENUM ('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'TENANT_SWITCH', 'TENANT_SWITCH_DENIED', 'UNAUTHORIZED_ACCESS', 'ADMIN_ACTION', 'PASSWORD_CHANGED', 'INVITATION_SENT', 'INVITATION_ACCEPTED', 'COMPANY_REGISTERED', 'ONBOARDING_COMPLETED', 'LEAD_CREATED', 'DEAL_UPDATED', 'API_QUERY', 'SYSTEM_STATUS_CHANGE');

-- AlterTable
ALTER TABLE "AuditEvent" ALTER COLUMN "eventType" TYPE "AuditEventType" USING ("eventType"::"AuditEventType");
